import {
  Activity,
  AlertTriangle,
  ArrowDownUp,
  BarChart3,
  BatteryCharging,
  Bell,
  CalendarClock,
  CloudSun,
  Coins,
  CreditCard,
  Database,
  FileCheck,
  Gauge,
  Gift,
  Globe,
  HeartPulse,
  History,
  House,
  LayoutDashboard,
  Leaf,
  MapPin,
  MessageSquare,
  Network,
  QrCode,
  Radio,
  Receipt,
  Settings,
  Shield,
  ShieldAlert,
  SlidersHorizontal,
  Sparkles,
  Sun,
  Target,
  Trophy,
  TrendingUp,
  Users,
  Wallet as WalletIcon,
  Workflow,
  Zap,
  type LucideIcon,
} from 'lucide-react';

/**
 * Icons are kept out of the route model so the model stays testable without
 * React, and out of the layout so this mapping can be asserted complete.
 */
export const NAV_ICONS: Record<string, LucideIcon> = {
  '/': LayoutDashboard,
  '/assets': Zap,
  '/monitoring': Activity,
  '/trading': TrendingUp,
  '/billing': Receipt,
  '/alerts': Bell,
  '/energy-insights': Zap,
  '/energy-analytics': BarChart3,
  '/analytics': BarChart3,
  '/insights/advisor': Sparkles,
  '/insights/solar-yield': Sun,
  '/insights/battery-health': BatteryCharging,
  '/insights/carbon': Leaf,
  '/market/order-book': ArrowDownUp,
  '/market/tariffs': TrendingUp,
  '/trading/price-alerts': Globe,
  '/trading/strategies': Target,
  '/trading/templates': FileCheck,
  '/trading/comparison': BarChart3,
  '/payments': CreditCard,
  '/wallet': WalletIcon,
  '/qr-payment': QrCode,
  '/referrals': Gift,
  '/digital-twin': Network,
  '/grid/control-windows': SlidersHorizontal,
  '/demand-response': Zap,
  '/v2g': CalendarClock,
  '/grid/price-signals': Coins,
  '/grid/locational-flexibility': MapPin,
  '/grid/forecast-accuracy': Target,
  '/grid/anomalies': AlertTriangle,
  '/grid/dr-forecast': CloudSun,
  '/grid/fleet-telemetry': Activity,
  '/grid/matter-loads': House,
  '/grid/degraded-operation': HeartPulse,
  '/grid/ntl': ShieldAlert,
  '/grid/compliance-reports': FileCheck,
  '/grid/operations-wall': Radio,
  '/community-pools': Users,
  '/leaderboard': Trophy,
  '/referral-leaderboard': Trophy,
  '/sms-center': MessageSquare,
  '/qr-scanner': QrCode,
  '/qr-generator': QrCode,
  '/qr-history': History,
  '/qr-device': QrCode,
  '/settings': Settings,
  '/notifications': Bell,
  '/biometric-settings': Shield,
  '/admin': Shield,
  '/admin/users': Users,
  '/admin/assets': Zap,
  '/admin/pricing': Coins,
  '/admin/devices': SlidersHorizontal,
  '/admin/iot-devices': Radio,
  '/admin/demand-response': Zap,
  '/admin/dr-automation': Workflow,
  '/admin/grid-operator': Network,
  '/admin/payment-credentials': CreditCard,
  '/admin/reconciliation': Receipt,
  '/admin/webhook-config': Globe,
  '/admin/analytics': BarChart3,
  '/admin/analytics-dashboard': BarChart3,
  '/admin/ml-predictions': Sparkles,
  '/admin/workflows': Workflow,
  '/admin/audit-logs': FileCheck,
  '/admin/cache-monitoring': Database,
  '/admin/performance': Gauge,
};
