CREATE INDEX "alerts_user_idx" ON "alerts" USING btree ("userId");--> statement-breakpoint
CREATE INDEX "assets_user_idx" ON "assets" USING btree ("userId");--> statement-breakpoint
CREATE INDEX "audit_logs_created_idx" ON "audit_logs" USING btree ("created_at");--> statement-breakpoint
CREATE INDEX "billings_user_idx" ON "billings" USING btree ("userId");--> statement-breakpoint
CREATE INDEX "biometric_credentials_user_idx" ON "biometric_credentials" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "contracts_user_idx" ON "contracts" USING btree ("userId");--> statement-breakpoint
CREATE INDEX "demand_response_events_status_idx" ON "demandResponseEvents" USING btree ("status");--> statement-breakpoint
CREATE INDEX "device_commands_device_idx" ON "device_commands" USING btree ("deviceId");--> statement-breakpoint
CREATE INDEX "device_logs_device_idx" ON "device_logs" USING btree ("deviceId");--> statement-breakpoint
CREATE INDEX "devices_asset_idx" ON "devices" USING btree ("assetId");--> statement-breakpoint
CREATE INDEX "dr_compensation_user_idx" ON "drCompensation" USING btree ("userId");--> statement-breakpoint
CREATE INDEX "dr_participants_user_idx" ON "drParticipants" USING btree ("userId");--> statement-breakpoint
CREATE INDEX "dr_responses_event_idx" ON "drResponses" USING btree ("eventId");--> statement-breakpoint
CREATE INDEX "dr_responses_user_idx" ON "drResponses" USING btree ("userId");--> statement-breakpoint
CREATE INDEX "grid_monitoring_ts_idx" ON "grid_monitoring" USING btree ("timestamp");--> statement-breakpoint
CREATE INDEX "leaderboard_entries_period_idx" ON "leaderboard_entries" USING btree ("period","period_start");--> statement-breakpoint
CREATE INDEX "leaderboard_entries_user_idx" ON "leaderboard_entries" USING btree ("user_id","period");--> statement-breakpoint
CREATE INDEX "market_prices_country_ts_idx" ON "marketPrices" USING btree ("country","timestamp");--> statement-breakpoint
CREATE INDEX "market_prices_ts_idx" ON "marketPrices" USING btree ("timestamp");--> statement-breakpoint
CREATE INDEX "payments_user_status_idx" ON "payments" USING btree ("userId","status");--> statement-breakpoint
CREATE INDEX "payments_status_created_idx" ON "payments" USING btree ("status","createdAt");--> statement-breakpoint
CREATE INDEX "payments_billing_idx" ON "payments" USING btree ("billingId");--> statement-breakpoint
CREATE INDEX "payments_transaction_idx" ON "payments" USING btree ("transactionId");--> statement-breakpoint
CREATE INDEX "payments_p2p_trade_idx" ON "payments" USING btree ("p2pTradeId");--> statement-breakpoint
CREATE INDEX "price_alerts_user_idx" ON "price_alerts" USING btree ("userId");--> statement-breakpoint
CREATE INDEX "referral_rewards_user_idx" ON "referral_rewards" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "referrals_referrer_idx" ON "referrals" USING btree ("referrer_id");--> statement-breakpoint
CREATE INDEX "tokens_payment_idx" ON "tokens" USING btree ("paymentId");--> statement-breakpoint
CREATE INDEX "trades_user_status_idx" ON "trades" USING btree ("userId","status");--> statement-breakpoint
CREATE INDEX "trades_status_created_idx" ON "trades" USING btree ("status","createdAt");--> statement-breakpoint
CREATE INDEX "trading_strategies_user_idx" ON "trading_strategies" USING btree ("userId");--> statement-breakpoint
CREATE INDEX "user_achievements_user_idx" ON "user_achievements" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "qr_code_history_user_idx" ON "qr_code_history" USING btree ("user_id","created_at");