"""Where a training set comes from, stated as one of three origins.

`platform`  — the operational Postgres tables, read directly.
`lakehouse` — Parquet objects a succeeded ingestion run wrote, every one re-hashed.
`synthetic` — generated by `vppml.synthetic` from a recorded seed.

The origin is resolved here, once, and travels into `training_datasets.origin`.
Nothing in this module can fall back from one origin to another: asking for a
lakehouse dataset when the lake is unconfigured or empty raises, rather than
reading the platform tables and calling the result lake-derived. That
substitution is the exact failure this layer is guarding against — a model whose
stated training data is not its training data.

Asset capacity and type always come from the `assets` table, including for a lake
dataset, because they are registration facts rather than measurements. For a
synthetic dataset they come from the generated fleet.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from datetime import datetime
from typing import Any, Optional

from . import lake, synthetic
from .config import Config
from .lake import LakeError, LakeReader


class DataError(RuntimeError):
    """The requested training data does not exist, or cannot be verified."""


@dataclass
class TrainingSource:
    origin: str
    columns: dict[str, list[Any]]
    asset_kinds: dict[int, str]
    asset_capacities: dict[int, int]
    #: asset id -> grid node id, and node -> parent, for the topology model.
    asset_nodes: dict[int, int] = field(default_factory=dict)
    node_parents: dict[int, Optional[int]] = field(default_factory=dict)
    object_keys: list[str] = field(default_factory=list)
    object_digests: list[str] = field(default_factory=list)
    generator: Optional[str] = None
    generator_version: Optional[str] = None
    seed: Optional[int] = None
    detail: str = ""

    @property
    def rows(self) -> int:
        if not self.columns:
            return 0
        return len(next(iter(self.columns.values())))


def asset_metadata(connection: Any) -> tuple[dict[int, str], dict[int, int]]:
    with connection.cursor() as cursor:
        cursor.execute('SELECT "id", "assetType", "capacity" FROM assets')
        kinds: dict[int, str] = {}
        capacities: dict[int, int] = {}
        for row in cursor.fetchall():
            asset_id = int(row[0])
            kinds[asset_id] = str(row[1])
            capacities[asset_id] = int(row[2] or 0)
    return kinds, capacities


def topology(connection: Any) -> tuple[dict[int, int], dict[int, Optional[int]]]:
    """The recorded grid topology: which node each asset hangs off, and each node's
    parent. Only links that exist are returned — an asset with no `grid_node_assets`
    row is absent from the graph rather than attached to a guessed node."""
    with connection.cursor() as cursor:
        cursor.execute("SELECT asset_id, node_id FROM grid_node_assets")
        asset_nodes = {int(row[0]): int(row[1]) for row in cursor.fetchall()}
        cursor.execute("SELECT id, parent_node_id FROM grid_nodes")
        node_parents = {
            int(row[0]): (int(row[1]) if row[1] is not None else None)
            for row in cursor.fetchall()
        }
    return asset_nodes, node_parents


def from_platform(
    connection: Any, *, window_start: datetime, window_end: datetime
) -> TrainingSource:
    kinds, capacities = asset_metadata(connection)
    with connection.cursor() as cursor:
        cursor.execute(
            """
            SELECT "assetId", "timestamp", "power", "energy", "stateOfCharge", "voltage"
              FROM telemetry
             WHERE "timestamp" >= %s AND "timestamp" < %s
             ORDER BY "assetId", "timestamp"
            """,
            (window_start, window_end),
        )
        rows = cursor.fetchall()
    columns: dict[str, list[Any]] = {
        "assetId": [row[0] for row in rows],
        "timestamp": [row[1] for row in rows],
        "power": [row[2] for row in rows],
        "energy": [row[3] for row in rows],
        "stateOfCharge": [row[4] for row in rows],
        "voltage": [row[5] for row in rows],
    }
    asset_nodes, node_parents = topology(connection)
    return TrainingSource(
        origin="platform",
        columns=columns,
        asset_kinds=kinds,
        asset_capacities=capacities,
        asset_nodes=asset_nodes,
        node_parents=node_parents,
        detail=f"{len(rows)} telemetry row(s) read from the platform database",
    )


def from_lakehouse(
    connection: Any, config: Config, *, window_start: datetime, window_end: datetime
) -> TrainingSource:
    if config.lake is None:
        raise DataError(
            "LAKEHOUSE_STORE is not configured, so there is no lake to train from. This run "
            "refuses rather than reading the platform tables and recording them as lake data."
        )
    reader = LakeReader(config.lake)
    try:
        extract = lake.extract(
            connection,
            reader,
            "telemetry",
            window_start,
            window_end,
            required_columns=("assetId", "timestamp", "power"),
        )
    except LakeError as exc:
        raise DataError(str(exc)) from exc

    kinds, capacities = asset_metadata(connection)
    asset_nodes, node_parents = topology(connection)
    return TrainingSource(
        origin="lakehouse",
        columns=extract.columns,
        asset_kinds=kinds,
        asset_capacities=capacities,
        asset_nodes=asset_nodes,
        node_parents=node_parents,
        object_keys=extract.object_keys,
        object_digests=extract.object_digests,
        detail=(
            f"{extract.rows} row(s) from {len(extract.object_keys)} verified object(s) in "
            f"{reader.describe()}"
        ),
    )


def from_synthetic(
    *,
    seed: int,
    window_start: datetime,
    hours: int,
    interval_minutes: int = 15,
) -> TrainingSource:
    fleet = synthetic.build_fleet(seed)
    columns = synthetic.generate(
        fleet, start=window_start, hours=hours, interval_minutes=interval_minutes
    )
    return TrainingSource(
        origin="synthetic",
        columns=columns,
        asset_kinds=synthetic.asset_kinds(fleet),
        asset_capacities=synthetic.asset_capacities(fleet),
        asset_nodes=synthetic.asset_nodes(fleet),
        node_parents=fleet.node_parents,
        generator=synthetic.GENERATOR_NAME,
        generator_version=synthetic.GENERATOR_VERSION,
        seed=seed,
        detail=(
            f"{len(columns['assetId'])} generated row(s) for {len(fleet.assets)} asset(s) "
            f"from seed {seed} ({synthetic.GENERATOR_NAME} v{synthetic.GENERATOR_VERSION})"
        ),
    )


def resolve(
    connection: Optional[Any],
    config: Optional[Config],
    origin: str,
    *,
    window_start: datetime,
    window_end: datetime,
    seed: Optional[int] = None,
    interval_minutes: int = 15,
) -> TrainingSource:
    if origin == "synthetic":
        if seed is None:
            raise DataError("a synthetic dataset needs a seed; without one it is not reproducible")
        hours = max(1, int((window_end - window_start).total_seconds() // 3600))
        return from_synthetic(
            seed=seed,
            window_start=window_start,
            hours=hours,
            interval_minutes=interval_minutes,
        )
    if connection is None:
        raise DataError(f"a {origin} dataset needs a database connection")
    if origin == "platform":
        return from_platform(connection, window_start=window_start, window_end=window_end)
    if origin == "lakehouse":
        if config is None:
            raise DataError("a lakehouse dataset needs the service configuration")
        return from_lakehouse(
            connection, config, window_start=window_start, window_end=window_end
        )
    raise DataError(f"unknown origin {origin!r}")
