/**
 * Weekly Digest Engine (innovation 15)
 *
 * Users opt in per channel (email / SMS). `runWeeklyDigests()` — wired to a
 * weekly cron by the platform scheduler — compiles each subscriber's real
 * stats for the ISO week that just ended (consumption from meter telemetry,
 * generation from solar telemetry, completed payments, vended tokens) and
 * dispatches them through the real channel services
 * (server/_core/emailService.ts SMTP, server/_core/notifications.ts SMS via
 * Africa's Talking).
 *
 * Every dispatch attempt is recorded as a digest_runs row with the exact
 * stats that were compiled and the real outcome:
 *  - `sent`    — the channel service confirmed acceptance,
 *  - `failed`  — the channel service refused or errored; `error` says why,
 *  - `skipped` — not attempted (e.g. no email address on file); `error`
 *    says why.
 * A failed run is never rewritten to sent; a later retry is a new run for a
 * new week (the (subscriptionId, periodStart) unique key makes reruns of
 * the same week idempotent no-ops).
 *
 * Stats are null where the underlying data does not exist, and the message
 * says "no data" for those sections — a week without telemetry is reported
 * as unknown, never as a fabricated zero.
 */

import { and, desc, eq, gte, lt, sql } from 'drizzle-orm';
import { getDb } from '../db';
import { assets, payments, telemetry, tokens, users } from '../../drizzle/schema';
import {
  digestRuns,
  digestSubscriptions,
  type DigestRun,
  type DigestSubscription,
} from '../../drizzle/innov3-market-schema';
import { sendEmail } from '../_core/emailService';
import { sendSMS } from '../_core/notifications';
import { getConsumptionWh } from './innov3-challenges';

async function requireDb() {
  const db = await getDb();
  if (!db) throw new Error('Database not available');
  return db;
}

// ---------------------------------------------------------------------------
// Subscriptions
// ---------------------------------------------------------------------------

/**
 * Opt in (or re-enable) a channel. Requires the user to actually have the
 * contact the channel needs — subscribing to SMS without a phone number is
 * refused, not silently accepted. Throws USER_NOT_FOUND /
 * NO_EMAIL_ON_FILE / NO_PHONE_ON_FILE.
 */
export async function subscribeDigest(userId: number, channel: 'email' | 'sms'): Promise<DigestSubscription> {
  const db = await requireDb();
  const [user] = await db.select({ email: users.email, phone: users.phone }).from(users).where(eq(users.id, userId)).limit(1);
  if (!user) throw new Error('USER_NOT_FOUND');
  if (channel === 'email' && !user.email) throw new Error('NO_EMAIL_ON_FILE');
  if (channel === 'sms' && !user.phone) throw new Error('NO_PHONE_ON_FILE');

  const [sub] = await db
    .insert(digestSubscriptions)
    .values({ userId, channel, enabled: true })
    .onConflictDoUpdate({
      target: [digestSubscriptions.userId, digestSubscriptions.channel],
      set: { enabled: true },
    })
    .returning();
  return sub;
}

export async function unsubscribeDigest(userId: number, channel: 'email' | 'sms'): Promise<DigestSubscription> {
  const db = await requireDb();
  const updated = await db
    .update(digestSubscriptions)
    .set({ enabled: false })
    .where(and(eq(digestSubscriptions.userId, userId), eq(digestSubscriptions.channel, channel)))
    .returning();
  if (updated.length === 0) throw new Error('SUBSCRIPTION_NOT_FOUND');
  return updated[0];
}

export async function listMySubscriptions(userId: number): Promise<DigestSubscription[]> {
  const db = await requireDb();
  return db.select().from(digestSubscriptions).where(eq(digestSubscriptions.userId, userId));
}

export async function listMyRuns(userId: number, opts: { limit: number }): Promise<DigestRun[]> {
  const db = await requireDb();
  return db
    .select()
    .from(digestRuns)
    .where(eq(digestRuns.userId, userId))
    .orderBy(desc(digestRuns.periodStart))
    .limit(opts.limit);
}

// ---------------------------------------------------------------------------
// Weekly stats compilation (all real, all nullable)
// ---------------------------------------------------------------------------

export interface WeeklyStats {
  periodStart: string;
  periodEnd: string;
  /** Wh consumed by meter assets; null when no meter reported. */
  consumptionWh: number | null;
  /** Wh generated by solar assets; null when no solar asset reported. */
  generationWh: number | null;
  /** Completed payments in the period, grouped by currency (never mixed). */
  payments: Array<{ currency: string; totalCents: number; count: number }>;
  /** Prepaid tokens vended in the period. */
  tokens: { count: number; totalEnergyKwh: number };
}

async function getGenerationWh(userId: number, start: Date, end: Date): Promise<number | null> {
  const db = await requireDb();
  const solarAssets = await db
    .select({ id: assets.id })
    .from(assets)
    .where(and(eq(assets.userId, userId), eq(assets.assetType, 'solar')));

  let totalWh = 0;
  let assetsWithData = 0;
  for (const asset of solarAssets) {
    const [agg] = await db
      .select({
        minEnergy: sql<number | null>`MIN(${telemetry.energy})`,
        maxEnergy: sql<number | null>`MAX(${telemetry.energy})`,
      })
      .from(telemetry)
      .where(and(eq(telemetry.assetId, asset.id), gte(telemetry.timestamp, start), lt(telemetry.timestamp, end)));
    if (agg?.minEnergy != null && agg?.maxEnergy != null && agg.maxEnergy >= agg.minEnergy) {
      totalWh += agg.maxEnergy - agg.minEnergy;
      assetsWithData++;
    }
  }
  return assetsWithData === 0 ? null : totalWh;
}

export async function compileWeeklyStats(userId: number, periodStart: Date, periodEnd: Date): Promise<WeeklyStats> {
  const db = await requireDb();

  const consumption = await getConsumptionWh(userId, periodStart, periodEnd);
  const generationWh = await getGenerationWh(userId, periodStart, periodEnd);

  const paymentRows = await db
    .select({
      currency: payments.currency,
      totalCents: sql<number>`SUM(${payments.amount})`,
      count: sql<number>`COUNT(*)`,
    })
    .from(payments)
    .where(
      and(
        eq(payments.userId, userId),
        eq(payments.status, 'completed'),
        gte(payments.createdAt, periodStart),
        lt(payments.createdAt, periodEnd)
      )
    )
    .groupBy(payments.currency);

  const [tokenAgg] = await db
    .select({
      count: sql<number>`COUNT(*)`,
      totalEnergyKwh: sql<number>`COALESCE(SUM(${tokens.energyKwh}), 0)`,
    })
    .from(tokens)
    .where(and(eq(tokens.userId, userId), gte(tokens.createdAt, periodStart), lt(tokens.createdAt, periodEnd)));

  return {
    periodStart: periodStart.toISOString(),
    periodEnd: periodEnd.toISOString(),
    consumptionWh: consumption.totalWh,
    generationWh,
    payments: paymentRows.map((r) => ({ currency: r.currency, totalCents: Number(r.totalCents), count: Number(r.count) })),
    tokens: { count: Number(tokenAgg?.count ?? 0), totalEnergyKwh: Number(tokenAgg?.totalEnergyKwh ?? 0) },
  };
}

// ---------------------------------------------------------------------------
// Message rendering
// ---------------------------------------------------------------------------

function kwh(wh: number | null): string {
  return wh === null ? 'no data' : `${(wh / 1000).toFixed(2)} kWh`;
}

export function renderDigestText(stats: WeeklyStats): string {
  const lines = [
    `Your VPP weekly digest (${stats.periodStart.slice(0, 10)} to ${stats.periodEnd.slice(0, 10)})`,
    `Consumption: ${kwh(stats.consumptionWh)}`,
    `Solar generation: ${kwh(stats.generationWh)}`,
  ];
  if (stats.payments.length === 0) {
    lines.push('Payments: none completed this week');
  } else {
    for (const p of stats.payments) {
      lines.push(`Payments (${p.currency}): ${(p.totalCents / 100).toFixed(2)} across ${p.count} payment(s)`);
    }
  }
  lines.push(
    stats.tokens.count === 0
      ? 'Prepaid tokens: none vended this week'
      : `Prepaid tokens: ${stats.tokens.count} vended (${stats.tokens.totalEnergyKwh} kWh total)`
  );
  return lines.join('\n');
}

function renderDigestHtml(stats: WeeklyStats): string {
  const rows = [
    `<tr><th>Consumption</th><td>${kwh(stats.consumptionWh)}</td></tr>`,
    `<tr><th>Solar generation</th><td>${kwh(stats.generationWh)}</td></tr>`,
    `<tr><th>Payments</th><td>${
      stats.payments.length === 0
        ? 'none completed this week'
        : stats.payments.map((p) => `${p.currency} ${(p.totalCents / 100).toFixed(2)} (${p.count})`).join('<br>')
    }</td></tr>`,
    `<tr><th>Prepaid tokens</th><td>${
      stats.tokens.count === 0 ? 'none vended this week' : `${stats.tokens.count} (${stats.tokens.totalEnergyKwh} kWh)`
    }</td></tr>`,
  ];
  return `<h2>Your weekly energy digest</h2><p>${stats.periodStart.slice(0, 10)} to ${stats.periodEnd.slice(0, 10)}</p><table>${rows.join('')}</table>`;
}

// ---------------------------------------------------------------------------
// Weekly run
// ---------------------------------------------------------------------------

/**
 * Start of the current ISO week (Monday 00:00 UTC). The digested week is
 * [isoWeekStart(now) - 7d, isoWeekStart(now)).
 */
export function isoWeekStart(now: Date): Date {
  const midnightUtc = Date.UTC(now.getUTCFullYear(), now.getUTCMonth(), now.getUTCDate());
  const day = (now.getUTCDay() + 6) % 7; // Monday = 0
  return new Date(midnightUtc - day * 86400000);
}

export interface WeeklyRunSummary {
  periodStart: string;
  periodEnd: string;
  enabledSubscriptions: number;
  alreadyProcessed: number;
  sent: number;
  failed: number;
  skipped: number;
}

/**
 * Compile and dispatch the weekly digest to every enabled subscriber.
 * Idempotent per week: a recipient with a digest_runs row for this week's
 * periodStart (any status) is not re-sent.
 */
export async function runWeeklyDigests(now: Date = new Date()): Promise<WeeklyRunSummary> {
  const db = await requireDb();

  const periodEnd = isoWeekStart(now);
  const periodStart = new Date(periodEnd.getTime() - 7 * 86400000);

  const subs = await db.select().from(digestSubscriptions).where(eq(digestSubscriptions.enabled, true));

  const summary: WeeklyRunSummary = {
    periodStart: periodStart.toISOString(),
    periodEnd: periodEnd.toISOString(),
    enabledSubscriptions: subs.length,
    alreadyProcessed: 0,
    sent: 0,
    failed: 0,
    skipped: 0,
  };

  for (const sub of subs) {
    const [existing] = await db
      .select({ id: digestRuns.id })
      .from(digestRuns)
      .where(and(eq(digestRuns.subscriptionId, sub.id), eq(digestRuns.periodStart, periodStart)))
      .limit(1);
    if (existing) {
      summary.alreadyProcessed++;
      continue;
    }

    const stats = await compileWeeklyStats(sub.userId, periodStart, periodEnd);
    const text = renderDigestText(stats);

    let status: 'sent' | 'failed' | 'skipped';
    let error: string | null = null;

    const [user] = await db.select({ email: users.email, phone: users.phone }).from(users).where(eq(users.id, sub.userId)).limit(1);

    if (sub.channel === 'email') {
      if (!user?.email) {
        status = 'skipped';
        error = 'no email address on file';
      } else {
        const result = await sendEmail({
          to: user.email,
          subject: `Your VPP weekly digest (${stats.periodStart.slice(0, 10)} – ${stats.periodEnd.slice(0, 10)})`,
          html: renderDigestHtml(stats),
          text,
        });
        status = result.success ? 'sent' : 'failed';
        error = result.success ? null : result.error ?? 'email service returned failure';
      }
    } else {
      if (!user?.phone) {
        status = 'skipped';
        error = 'no phone number on file';
      } else if (!process.env.AT_API_KEY || !process.env.AT_USERNAME) {
        // Mirror of notifications.sendSMS's own configuration gate, so the
        // run row records the real reason instead of a bare false.
        status = 'failed';
        error = "SMS gateway not configured (AT_API_KEY/AT_USERNAME missing)";
      } else {
        const ok = await sendSMS({ to: user.phone, message: text });
        status = ok ? 'sent' : 'failed';
        error = ok ? null : 'SMS delivery refused by gateway';
      }
    }

    await db.insert(digestRuns).values({
      subscriptionId: sub.id,
      userId: sub.userId,
      channel: sub.channel,
      periodStart,
      periodEnd,
      stats: stats as unknown as Record<string, unknown>,
      status,
      error,
      sentAt: status === 'sent' ? new Date() : null,
    });

    summary[status]++;
  }

  return summary;
}
